### ISSUE TITLE
Initial startup: Database tables do not exist

### ISSUE THREAD

**Issue by xorbitwise** [WildEyeConservation/TrapTagger#3]
When I first execute `docker-compose up`, the containers start, but then most have errors because no tables exist in the database.
I can see there is a `migrations/versions/` directory for alembic, but I am unsure how to initially create the tables.

Thank you.

**Comment by NicholasOsner** [comment]
Apologies, I was on leave at the time and subsequently missed this.

Everything was set up correctly at the time of open sourcing, but I see I added some steps to the initialisation process that resulted in the app falling over before it got to the database setup. I have corrected this by bypassing the above steps when the app is in maintenance mode. So all you will need to do is start the app up in maintenance mode the first time, and it will do all the necessary database initialisation. Thereafter, you can just restart it in normal mode.

I have corrected the mistake in the development branch, and will be merging that into the main branch in the next few days.
